enable-blacklist: True
default-item-distribution: "2,6,9,6,2"
default-num-lines-complete-for-win: 1
show-currently-winning-team: True
notify-other-team-completions: True
prevent-water-spawns: True
show-all-maps-after-game: True
give-all-recipes: True
freeze-time-on-start: 5
notify-progress:
  lines:
    - each
  full-card:
    - 10
    - 20
    - 23
  lockout:
    - 5
    - 10
border:
  enable: True
  overworld-size: 3000
  nether-size: 1000
timer:
  enable: True
  length: 1800
pregeneration-mode:
  enable: False
pregame:
  border-radius: 20

# new stuffs in fallen's fork
auto-save-disabled: True
spawn-locations-chunk-loading-radius: 0
default-win-condition-is-quidditch: False
quidditch-golden-snitch-bonus: 1
allow-mid-game-join: False
allow-spawn-biome-without-tree: True
